// <auto-generated />
using System;
using MagicVila_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilaWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVila_WebAPI.Models.Vila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amaenity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqrft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vilas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amaenity = "",
                            CreatedDate = new DateTime(2023, 1, 26, 21, 1, 17, 262, DateTimeKind.Local).AddTicks(2885),
                            Details = "Have fun and enjoy yourself",
                            ImageUrl = "",
                            Name = "Villa pool",
                            Occupancy = 4,
                            Rate = 4.0,
                            Sqrft = 100,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amaenity = "",
                            CreatedDate = new DateTime(2023, 1, 26, 21, 1, 17, 262, DateTimeKind.Local).AddTicks(2897),
                            Details = "A place to explore the world",
                            ImageUrl = "",
                            Name = "Villa beach",
                            Occupancy = 0,
                            Rate = 5.0,
                            Sqrft = 150,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MagicVila_WebAPI.Models.VilaNumber", b =>
                {
                    b.Property<int>("VilaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VilaID")
                        .HasColumnType("int");

                    b.HasKey("VilaNo");

                    b.HasIndex("VilaID");

                    b.ToTable("VilaNumbers");
                });

            modelBuilder.Entity("MagicVila_WebAPI.Models.VilaNumber", b =>
                {
                    b.HasOne("MagicVila_WebAPI.Models.Vila", "Vila")
                        .WithMany()
                        .HasForeignKey("VilaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vila");
                });
#pragma warning restore 612, 618
        }
    }
}
